// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6JRS4POzegeRZw1QjKpaxBKoNR-Vn24',
    appId: '1:179997314991:web:c1ec70eefa8b2c5483295a',
    messagingSenderId: '179997314991',
    projectId: 'time-tracker-jm',
    authDomain: 'time-tracker-jm.firebaseapp.com',
    storageBucket: 'time-tracker-jm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5fj7v4fkwtevt7Y2NQy7EI55t28JuFg',
    appId: '1:179997314991:android:0af4e7711c712e1f83295a',
    messagingSenderId: '179997314991',
    projectId: 'time-tracker-jm',
    storageBucket: 'time-tracker-jm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmnV760OMPZ8ZW77Fguu_Xjy1z-bZCgM',
    appId: '1:179997314991:ios:2dff8fee6c97e5ec83295a',
    messagingSenderId: '179997314991',
    projectId: 'time-tracker-jm',
    storageBucket: 'time-tracker-jm.firebasestorage.app',
    iosBundleId: 'com.jmitchell238.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmnV760OMPZ8ZW77Fguu_Xjy1z-bZCgM',
    appId: '1:179997314991:ios:2dff8fee6c97e5ec83295a',
    messagingSenderId: '179997314991',
    projectId: 'time-tracker-jm',
    storageBucket: 'time-tracker-jm.firebasestorage.app',
    iosBundleId: 'com.jmitchell238.timeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP6JRS4POzegeRZw1QjKpaxBKoNR-Vn24',
    appId: '1:179997314991:web:54147da1282865d683295a',
    messagingSenderId: '179997314991',
    projectId: 'time-tracker-jm',
    authDomain: 'time-tracker-jm.firebaseapp.com',
    storageBucket: 'time-tracker-jm.firebasestorage.app',
  );
}
